<?php

	function helloworld_menu() {
		$items['helloworld-page'] = array (
			'title' => 'Hello World Page Title',
			'page callback' => 'helloworld_page',
			'access arguments' => array('access content'),
			'type' => MENU_CALLBACK ,
		);
		
		return $items;
	}
	
	function helloworld_page() {
		global $user;
		$name = $user->name;
		$output = "<ol>";
		
		for($i=0; $i < 10; $i++) {
			$output .= "<li>";
			$output .= "Hello, " .$name;
			$output .= "</li>";
		}
		
		$output .= "</ol>";
		
		return $output;
		
		
	}